name: content-web

# This workflow is triggered on push to the 'content-web' directory of the  master branch of the repository
on:
   push:
      branches:
         - master
      paths:
         - 'content-web/**'

   # Configure workflow to also support triggering manually
   workflow_dispatch:
      inputs:
         logLevel:
            description: 'Log level'
            required: true
            default: 'warning'

# Environment variables are defined so that they can be used throughout the job definitions.
env:
   imageRepository: 'content-web'
   resourceGroupName: 'fabmedical-274513'
   containerRegistryName: 'acr274513'
   containerRegistry: 'acr274513.azurecr.io'
   dockerfilePath: './content-web'
   tag: '${{ github.run_id  }}'

# Jobs define the actions that take place when code is pushed to the master branch
jobs:
   build-and-publish-docker-image:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest
      steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
            registry: ${{ env.containerRegistry }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push an image to container registry
        uses: docker/build-push-action@v2
        with:
            context: ${{ env.dockerfilePath  }}
            file: "${{ env.dockerfilePath }}/Dockerfile"
            pull: true
            push: true
            tags: |
               ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
               ${{ env.containerRegistry }}/${{ env.imageRepository }}:latest
